export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const LOGIN_AUTH_SAGA = 'LOGIN_AUTH_SAGA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

export const COMPLETE_NEW_PASSWORD = 'COMPLETE_NEW_PASSWORD';
export const COMPLETE_NEW_PASSWORD_SUCCESS = 'COMPLETE_NEW_PASSWORD_SUCCESS';
export const NEW_PASSWORD_ERROR = 'NEW_PASSWORD_ERROR';

export const IS_AUTHENTICATE = 'IS_AUTHENTICATE';
export const IS_AUTHENTICATE_ERROR = 'IS_AUTHENTICATE_ERROR';

export const RESEND_CODE = 'RESEND_CODE';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const RESEND_CODE_ERROR = 'RESEND_CODE_ERROR';
